# Generated by Django 4.2.1 on 2023-06-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_event_log_manage_ticket_users_delete_personal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manage_ticket',
            old_name='assignee',
            new_name='assigne',
        ),
    ]
